services:
    # MySQL (数据库)
    shop-mysql:
        image: mysql:latest
        volumes:
            - ./configs/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=easy-shop
            - MYSQL_USER=easy-shop
            - MYSQL_PASSWORD=easy-shop
            - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    # Redis (NoSQL 数据库)
    shop-redis:
        image: redis:6 # Go Redis v9 暂时没有正式发布
        ports:
            - "6379:6379"
    # Nacos (服务发现)
    shop-nacos:
        image: nacos/nacos-server:latest
        environment:
            - PREFER_HOST_MODE=hostname
            - MODE=standalone
        ports:
            - "8848:8848"
            - "9848:9848"
            - "9555:9555"
    # Jaeger，开源的、端到端的分布式链路追踪
    shop-jaeger-all-in-one:
        image: jaegertracing/all-in-one:latest
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - "16686:16686"
            - "14268"
            - "14250:14250"
            - "6831:6831"
    # Collector，OpenTelemetry是一个工具、API和SDK的集合。使用它来检测、生成、收集和导出遥测数据（指标、日志和跟踪），以帮助你分析你的软件的性能和行为
    shop-otel-collector:
        image: otel/opentelemetry-collector-contrib-dev:latest
        #, "${OTELCOL_ARGS}" ]
        command: [ "--config=/etc/otel-collector-config.yaml"]
        volumes:
            - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "1888:1888"   # pprof extension
            - "8888"        # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "4317:4317"   # OTLP gRPC receiver
            - "55679"       # zpages extension
        depends_on:
            - shop-jaeger-all-in-one
            - shop-victoriametrics
    # Victoriametrics (高性能的开源时间序列数据库和监测解决方案, 兼容 Prometheus)
    shop-victoriametrics:
        image: victoriametrics/victoria-metrics:latest
        ports:
            - "8428:8428"
            - "8089:8089"
            - "8089:8089/udp"
            - "2003:2003"
            - "2003:2003/udp"
            - "4242:4242"
        command:
            - '--storageDataPath=/storage'
            - '--graphiteListenAddr=:2003'
            - '--opentsdbListenAddr=:4242'
            - '--httpListenAddr=:8428'
            - '--influxListenAddr=:8089'
        # restart: always
    # Grafana (可视化数据的仪表盘)
    shop-grafana:
        image: grafana/grafana:latest
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3000:3000"
